spring.application.name=flashseat
spring.datasource.url=jdbc:postgresql://localhost:5432/flashseat
spring.datasource.username=postgres
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update